### ISSUE TITLE
validation layer errors

### ISSUE THREAD

**Issue by tpalli** [vga-group/tauray#38]
Following syncronization related issues can be seen with: VK_LAYER_ENABLES=VK_VALIDATION_FEATURE_ENABLE_SYNCHRONIZATION_VALIDATION_EXT

[tauray_validation.log](https://github.com/vga-group/tauray/files/11703552/tauray_validation.log)

**Comment by juliusikkala** [comment]
Thanks! I'll start testing with that layer separately in the future. Kind of forgot that it exists :laughing:
