### ISSUE TITLE
Scene file used in the paper

### ISSUE THREAD

**Issue by lhanafhk** [vga-group/tauray#41]
Great Work!
Can you kindly share the scene files used for comparisons between ddgi and DDISH-GI?

Best Regards

**Comment by juliusikkala** [comment]
Hi! Sorry for the long delay, I was on vacation and returned today.

We uploaded the .glb scenes and envmaps here: [https://webpages.tuni.fi/vga/publications/ddish-gi-paper-scenes.zip](https://webpages.tuni.fi/vga/publications/ddish-gi-paper-scenes.zip). We also included the old scripts we used back then, but I didn't check if they work with current Tauray anymore. That paper and its measurements were done before 1.0 and the public release, so there's a chance that some things in the old scripts don't work anymore. We haven't really focused on DDISH-GI recently, so there may be some "bitrot" as well. Hopefully these are useful to you.
