### ISSUE TITLE
validation errors

### ISSUE THREAD

**Issue by tpalli** [vga-group/tauray#6]
When running test.glb on Intel(R) Arc(tm) A770 Graphics I see multiple validation errors of following type:

`
Validation Error: [ VUID-vkCmdBuildAccelerationStructuresKHR-pInfos-03710 ] Object 0: handle = 0x55f2895b06e0, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x63ff8904 | vkCmdBuildAccelerationStructuresKHR:For each element of pInfos, its scratchData.deviceAddress member must be a multiple of VkPhysicalDeviceAccelerationStructurePropertiesKHR::minAccelerationStructureScratchOffsetAlignment. The Vulkan spec states: For each element of pInfos, its scratchData.deviceAddress member must be a multiple of VkPhysicalDeviceAccelerationStructurePropertiesKHR::minAccelerationStructureScratchOffsetAlignment (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkCmdBuildAccelerationStructuresKHR-pInfos-03710)
`
(minAccelerationStructureScratchOffsetAlignment for this device is 64)

**Comment by juliusikkala** [comment]
I've now made a PR that allocates the scratch buffers with alignment corresponding to minAccelerationStructureScratchOffsetAlignment. Can you test that it works? I don't personally have access to Intel Arc hardware yet.

**Comment by tpalli** [comment]
I've tested your PR and there are no more validation errors so this is fixed now. No correct rendering though, I will later try to investigate what could be wrong and that should be treated as separate issue.
